In [2]:
import time
import pandas as pd

from nba_api.stats.static import players
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog

In [3]:
active_players = players.get_active_players()
all_teams = teams.get_teams()

print(f"Active players: {len(active_players)}")
print(f"Teams: {len(all_teams)}")

Active players: 530
Teams: 30

In [4]:
active_players[:3]

[{'id': 1630173,
  'full_name': 'Precious Achiuwa',
  'first_name': 'Precious',
  'last_name': 'Achiuwa',
  'is_active': True},
 {'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams',
  'is_active': True},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True}]

In [5]:
all_teams[:3]

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Georgia',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970}]

In [6]:
lebron = players.find_players_by_full_name("LeBron James")
lebron_id = lebron[0]['id']
lebron_id

2544

In [7]:
gamelog = playergamelog.PlayerGameLog(player_id=lebron_id, season='2024-25')
df = gamelog.get_data_frames()[0]
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,...,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,...,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,...,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,...,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,...,0,0,8,2,0,1,1,27,7,1

In [8]:
df.columns

Index(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL',
       'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='str')

In [9]:
pd.set_option('display.max_columns', None)
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1

In [10]:
df.drop(columns=['VIDEO_AVAILABLE'])

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,22024,2544,0022400118,"Oct 30, 2024",LAL @ CLE,L,29,9,13,0.692,1,3,0.333,7,7,1.000,1,5,6,3,0,0,6,2,26,-17
66,22024,2544,0022400111,"Oct 28, 2024",LAL @ PHX,L,36,3,14,0.214,2,5,0.400,3,6,0.500,0,5,5,8,1,0,2,1,11,-17
67,22024,2544,0022400096,"Oct 26, 2024",LAL vs. SAC,W,34,12,22,0.545,4,9,0.444,4,4,1.000,0,14,14,10,0,1,5,3,32,13
68,22024,2544,0022400085,"Oct 25, 2024",LAL vs. PHX,W,35,7,13,0.538,2,5,0.400,5,8,0.625,0,4,4,8,0,0,2,1,21,14
69,22024,2544,0022400062,"Oct 22, 2024",LAL vs. MIN,W,35,7,16,0.438,1,4,0.250,1,1,1.000,0,5,5,4,0,2,2,3,16,-6

In [11]:
pd.set_option('display.max_rows', None)
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1

In [15]:
# Show full DataFrame — all rows and all columns, no truncation
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1
5,22024,2544,0022401117,"Apr 03, 2025",LAL vs. GSW,L,40,10,15,0.667,5,8,0.625,8,9,0.889,1,4,5,9,1,1,4,2,33,-1,1
6,22024,2544,0022401096,"Mar 31, 2025",LAL vs. HOU,W,38,5,12,0.417,2,4,0.500,4,4,1.000,0,8,8,4,2,2,3,1,16,9,1
7,22024,2544,0022401078,"Mar 29, 2025",LAL @ MEM,W,37,10,21,0.476,2,5,0.400,3,4,0.750,1,5,6,8,3,1,3,3,25,-1,1
8,22024,2544,0022401063,"Mar 27, 2025",LAL @ CHI,L,39,8,20,0.400,0,5,0.000,1,2,0.500,1,4,5,12,2,0,4,1,17,-10,1
9,22024,2544,0022401055,"Mar 26, 2025",LAL @ IND,W,38,4,12,0.333,0,3,0.000,5,5,1.000,3,10,13,7,1,0,1,1,13,5,1
10,22024,2544,0022401038,"Mar 24, 2025",LAL @ ORL,L,38,9,18,0.500,0,3,0.000,6,7,0.857,3,3,6,7,0,0,2,0,24,-17,1
11,22024,2544,0022401028,"Mar 22, 2025",LAL vs. CHI,L,31,7,16,0.438,1,2,0.500,2,5,0.400,0,6,6,4,3,0,5,1,17,-27,1
12,22024,2544,0022400918,"Mar 08, 2025",LAL @ BOS,L,35,11,23,0.478,0,6,0.000,0,3,0.000,2,12,14,9,0,0,1,3,22,-11,1
13,22024,2544,0022400903,"Mar 06, 2025",LAL vs. NYK,W,44,11,23,0.478,2,8,0.250,7,8,0.875,1,11,12,8,0,1,1,3,31,4,1
14,22024,2544,0022400890,"Mar 04, 2025",LAL vs. NOP,W,33,10,18,0.556,5,10,0.500,9,9,1.000,1,7,8,6,1,2,4,1,34,7,1
15,22024,2544,0022400874,"Mar 02, 2025",LAL vs. LAC,W,36,6,17,0.353,1,6,0.167,4,4,1.000,1,4,5,9,2,1,8,2,17,-5,1
16,22024,2544,0022400859,"Feb 28, 2025",LAL vs. LAC,W,37,12,21,0.571,2,7,0.286,2,3,0.667,1,12,13,3,1,0,4,0,28,-1,1
17,22024,2544,0022400849,"Feb 27, 2025",LAL vs. MIN,W,37,11,21,0.524,4,9,0.444,7,10,0.700,5,12,17,6,1,1,4,1,33,12,1
18,22024,2544,0022400835,"Feb 25, 2025",LAL vs. DAL,W,37,11,17,0.647,2,4,0.500,3,4,0.750,3,9,12,3,1,0,6,2,27,-5,1
19,22024,2544,0022400808,"Feb 22, 2025",LAL @ DEN,W,33,11,19,0.579,1,4,0.250,2,3,0.667,2,7,9,5,1,3,1,2,25,9,1
20,22024,2544,0022400796,"Feb 20, 2025",LAL @ POR,W,36,14,24,0.583,4,8,0.500,8,8,1.000,0,8,8,4,2,1,11,2,40,8,1
21,22024,2544,0022400524,"Feb 19, 2025",LAL vs. CHA,L,38,10,22,0.455,4,11,0.364,2,2,1.000,1,6,7,11,1,2,2,0,26,-4,1
22,22024,2544,0022400781,"Feb 12, 2025",LAL @ UTA,L,34,6,13,0.462,4,8,0.500,2,4,0.500,1,5,6,7,1,0,3,3,18,-10,1
23,22024,2544,0022400768,"Feb 10, 2025",LAL vs. UTA,W,29,10,17,0.588,3,7,0.429,1,2,0.500,1,6,7,8,1,0,7,2,24,24,1
24,22024,2544,0022400731,"Feb 06, 2025",LAL vs. GSW,W,38,14,25,0.560,6,9,0.667,8,10,0.800,1,16,17,8,1,1,3,1,42,7,1
25,22024,2544,0022400715,"Feb 04, 2025",LAL @ LAC,W,31,8,13,0.615,2,4,0.500,8,11,0.727,0,8,8,9,3,0,3,4,26,19,1
26,22024,2544,0022400692,"Feb 01, 2025",LAL @ NYK,W,37,14,26,0.538,3,8,0.375,2,4,0.500,0,11,11,12,0,0,5,3,33,12,1
27,22024,2544,0022400674,"Jan 30, 2025",LAL @ WAS,W,27,9,19,0.474,1,4,0.250,5,5,1.000,0,3,3,11,0,0,0,1,24,29,1
28,22024,2544,0022400660,"Jan 28, 2025",LAL @ PHI,L,33,10,16,0.625,1,4,0.250,10,11,0.909,1,7,8,9,1,0,8,1,31,-11,1
29,22024,2544,0022400648,"Jan 27, 2025",LAL @ CHA,W,36,9,17,0.529,1,8,0.125,3,5,0.600,0,7,7,8,0,0,5,0,22,-1,1
30,22024,2544,0022400644,"Jan 25, 2025",LAL @ GSW,W,35,12,25,0.480,0,1,0.000,1,2,0.500,1,4,5,12,1,0,3,0,25,11,1
31,22024,2544,0022400629,"Jan 23, 2025",LAL vs. BOS,W,31,9,20,0.450,0,2,0.000,2,2,1.000,3,11,14,6,0,0,2,0,20,7,1
32,22024,2544,0022400610,"Jan 21, 2025",LAL vs. WAS,W,36,8,18,0.444,2,6,0.333,3,3,1.000,0,10,10,13,2,1,5,0,21,19,1
33,22024,2544,0022400596,"Jan 19, 2025",LAL @ LAC,L,35,9,20,0.450,2,6,0.333,5,6,0.833,2,3,5,11,3,1,5,3,25,-3,1
34,22024,2544,0022400585,"Jan 17, 2025",LAL vs. BKN,W,35,12,17,0.706,4,6,0.667,1,2,0.500,1,6,7,8,1,2,5,2,29,-11,1
35,22024,2544,0022400570,"Jan 15, 2025",LAL vs. MIA,W,38,9,15,0.600,3,6,0.500,1,2,0.500,1,4,5,9,2,0,2,0,22,14,1
36,22024,2544,0022400552,"Jan 13, 2025",LAL vs. SAS,L,32,7,11,0.636,2,3,0.667,2,4,0.500,1,4,5,8,1,1,7,3,18,-15,1
37,22024,2544,0022400504,"Jan 07, 2025",LAL @ DAL,L,35,6,12,0.500,1,4,0.250,5,6,0.833,0,10,10,8,1,0,2,0,18,-12,1
38,22024,2544,0022400491,"Jan 05, 2025",LAL @ HOU,L,36,8,16,0.500,4,7,0.571,1,2,0.500,1,12,13,9,1,0,2,4,21,-13,1
39,22024,2544,0022400477,"Jan 03, 2025",LAL vs. ATL,W,30,13,20,0.650,2,5,0.400,2,2,1.000,0,3,3,8,0,0,3,3,30,4,1
40,22024,2544,0022400468,"Jan 02, 2025",LAL vs. POR,W,36,15,25,0.600,7,10,0.700,1,2,0.500,1,2,3,8,0,0,4,1,38,4,1
41,22024,2544,0022400454,"Dec 31, 2024",LAL vs. CLE,L,34,9,17,0.529,3,6,0.500,2,2,1.000,0,4,4,7,0,1,2,1,23,-11,1
42,22024,2544,0022400408,"Dec 25, 2024",LAL @ GSW,W,37,12,22,0.545,2,4,0.500,5,5,1.000,0,4,4,10,2,1,1,3,31,4,1
43,22024,2544,0022400404,"Dec 23, 2024",LAL vs. DET,L,35,10,16,0.625,2,4,0.500,6,7,0.857,2,9,11,11,0,0,2,1,28,-1,1
44,22024,2544,0022400376,"Dec 21, 2024",LAL @ SAC,W,34,13,24,0.542,1,8,0.125,5,6,0.833,0,7,7,6,4,0,4,2,32,10,1
45,22024,2544,0022400372,"Dec 19, 2024",LAL @ SAC,W,34,8,21,0.381,1,4,0.250,2,2,1.000,0,6,6,7,0,1,2,1,19,13,1
46,22024,2544,0022401220,"Dec 15, 2024",LAL vs. MEM,W,34,7,17,0.412,3,6,0.500,1,4,0.250,4,4,8,8,1,2,5,2,18,0,1
47,22024,2544,0022400334,"Dec 06, 2024",LAL @ ATL,L,43,14,25,0.560,6,11,0.545,5,6,0.833,0,10,10,11,2,3,4,3,39,3,1
48,22024,2544,0022400321,"Dec 04, 2024",LAL @ MIA,L,29,12,18,0.667,1,4,0.250,4,4,1.000,1,4,5,8,1,0,5,2,29,-21,1
49,22024,2544,0022400318,"Dec 02, 2024",LAL @ MIN,L,31,4,16,0.250,0,4,0.000,2,4,0.500,3,5,8,4,0,0,6,1,10,-28,1
50,22024,2544,0022400311,"Dec 01, 2024",LAL @ UTA,W,36,12,28,0.429,0,9,0.000,3,3,1.000,1,4,5,14,0,2,3,1,27,0,1
51,22024,2544,0022400048,"Nov 29, 2024",LAL vs. OKC,L,34,5,13,0.385,0,4,0.000,2,2,1.000,0,8,8,6,0,0,5,0,12,-12,1
52,22024,2544,0022400296,"Nov 27, 2024",LAL @ SAS,W,33,8,18,0.444,0,2,0.000,0,0,0.000,3,7,10,11,1,1,5,0,16,4,1
53,22024,2544,0022400039,"Nov 26, 2024",LAL @ PHX,L,35,7,16,0.438,2,7,0.286,2,2,1.000,1,7,8,10,0,0,5,0,18,-30,1
54,22024,2544,0022400270,"Nov 23, 2024",LAL vs. DEN,L,35,7,17,0.412,1,4,0.250,3,3,1.000,0,6,6,7,3,0,6,3,18,-25,1
55,22024,2544,0022400263,"Nov 21, 2024",LAL vs. ORL,L,37,12,22,0.545,5,9,0.556,2,4,0.500,2,8,10,7,0,1,4,0,31,-8,1
56,22024,2544,0022400026,"Nov 19, 2024",LAL vs. UTA,W,34,9,17,0.529,1,5,0.200,7,11,0.636,0,2,2,12,0,0,4,1,26,-5,1
57,22024,2544,0022400231,"Nov 16, 2024",LAL @ NOP,W,37,8,19,0.421,2,7,0.286,3,5,0.600,4,3,7,5,1,0,6,1,21,1,1
58,22024,2544,0022400015,"Nov 15, 2024",LAL @ SAS,W,38,6,12,0.500,1,4,0.250,2,4,0.500,1,15,16,12,1,0,7,0,15,3,1
59,22024,2544,0022400225,"Nov 13, 2024",LAL vs. MEM,W,37,13,22,0.591,4,7,0.571,5,8,0.625,1,11,12,14,1,0,6,2,35,3,1
60,22024,2544,0022400211,"Nov 10, 2024",LAL vs. TOR,W,35,6,14,0.429,0,3,0.000,7,7,1.000,2,8,10,16,1,0,3,0,19,13,1
61,22024,2544,0022400195,"Nov 08, 2024",LAL vs. PHI,W,34,9,14,0.643,2,4,0.500,1,1,1.000,0,12,12,13,0,3,2,0,21,12,1
62,22024,2544,0022400174,"Nov 06, 2024",LAL @ MEM,L,35,15,24,0.625,6,11,0.545,3,4,0.750,0,7,7,6,1,0,5,2,39,-21,1
63,22024,2544,0022400156,"Nov 04, 2024",LAL @ DET,L,40,7,16,0.438,1,2,0.500,5,5,1.000,1,7,8,11,2,0,1,1,20,-16,1
64,22024,2544,0022400137,"Nov 01, 2024",LAL @ TOR,W,36,9,17,0.529,5,8,0.625,4,6,0.667,0,6,6,10,1,0,0,1,27,11,1
65,22024,2544,0022400118,"Oct 30, 2024",LAL @ CLE,L,29,9,13,0.692,1,3,0.333,7,7,1.000,1,5,6,3,0,0,6,2,26,-17,1
66,22024,2544,0022400111,"Oct 28, 2024",LAL @ PHX,L,36,3,14,0.214,2,5,0.400,3,6,0.500,0,5,5,8,1,0,2,1,11,-17,1
67,22024,2544,0022400096,"Oct 26, 2024",LAL vs. SAC,W,34,12,22,0.545,4,9,0.444,4,4,1.000,0,14,14,10,0,1,5,3,32,13,1
68,22024,2544,0022400085,"Oct 25, 2024",LAL vs. PHX,W,35,7,13,0.538,2,5,0.400,5,8,0.625,0,4,4,8,0,0,2,1,21,14,1
69,22024,2544,0022400062,"Oct 22, 2024",LAL vs. MIN,W,35,7,16,0.438,1,4,0.250,1,1,1.000,0,5,5,4,0,2,2,3,16,-6,1

In [ ]:
# SQL Views to reduce 3NF violations and transitive dependency w/ %s and oreb dreb categories:
# sql view to calculate fg, fg3, ft percentages
#CREATE VIEW game_logs_with_pct AS
#SELECT
#    *,
#    ROUND(FGM::numeric / NULLIF(FGA, 0), 3) AS fg_pct,
#    ROUND(FG3M::numeric / NULLIF(FG3A, 0), 3) AS fg3_pct,
#    ROUND(FTM::numeric / NULLIF(FTA, 0), 3) AS ft_pct
#FROM game_logs;

# sql view to calculate total rebounds 
#CREATE VIEW game_logs_with_totals AS
#SELECT
#    *,
#    OREB + DREB AS reb
# FROM game_logs;

In [13]:
df.drop(columns=['FG_PCT', 'FG3_PCT', 'FT_PCT', 'REB', 'VIDEO_AVAILABLE'])

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,1,4,1,1,0,4,8,1,0,1,1,14,5
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0,4,5,6,2,5,3,1,0,2,2,27,18
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,3,6,9,10,0,7,3,1,0,6,1,28,-23
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,1,1,0,0,2,1,7,1,0,2,0,19,7
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,2,7,7,8,0,0,8,2,0,1,1,27,7
5,22024,2544,0022401117,"Apr 03, 2025",LAL vs. GSW,L,40,10,15,5,8,8,9,1,4,9,1,1,4,2,33,-1
6,22024,2544,0022401096,"Mar 31, 2025",LAL vs. HOU,W,38,5,12,2,4,4,4,0,8,4,2,2,3,1,16,9
7,22024,2544,0022401078,"Mar 29, 2025",LAL @ MEM,W,37,10,21,2,5,3,4,1,5,8,3,1,3,3,25,-1
8,22024,2544,0022401063,"Mar 27, 2025",LAL @ CHI,L,39,8,20,0,5,1,2,1,4,12,2,0,4,1,17,-10
9,22024,2544,0022401055,"Mar 26, 2025",LAL @ IND,W,38,4,12,0,3,5,5,3,10,7,1,0,1,1,13,5
10,22024,2544,0022401038,"Mar 24, 2025",LAL @ ORL,L,38,9,18,0,3,6,7,3,3,7,0,0,2,0,24,-17
11,22024,2544,0022401028,"Mar 22, 2025",LAL vs. CHI,L,31,7,16,1,2,2,5,0,6,4,3,0,5,1,17,-27
12,22024,2544,0022400918,"Mar 08, 2025",LAL @ BOS,L,35,11,23,0,6,0,3,2,12,9,0,0,1,3,22,-11
13,22024,2544,0022400903,"Mar 06, 2025",LAL vs. NYK,W,44,11,23,2,8,7,8,1,11,8,0,1,1,3,31,4
14,22024,2544,0022400890,"Mar 04, 2025",LAL vs. NOP,W,33,10,18,5,10,9,9,1,7,6,1,2,4,1,34,7
15,22024,2544,0022400874,"Mar 02, 2025",LAL vs. LAC,W,36,6,17,1,6,4,4,1,4,9,2,1,8,2,17,-5
16,22024,2544,0022400859,"Feb 28, 2025",LAL vs. LAC,W,37,12,21,2,7,2,3,1,12,3,1,0,4,0,28,-1
17,22024,2544,0022400849,"Feb 27, 2025",LAL vs. MIN,W,37,11,21,4,9,7,10,5,12,6,1,1,4,1,33,12
18,22024,2544,0022400835,"Feb 25, 2025",LAL vs. DAL,W,37,11,17,2,4,3,4,3,9,3,1,0,6,2,27,-5
19,22024,2544,0022400808,"Feb 22, 2025",LAL @ DEN,W,33,11,19,1,4,2,3,2,7,5,1,3,1,2,25,9
20,22024,2544,0022400796,"Feb 20, 2025",LAL @ POR,W,36,14,24,4,8,8,8,0,8,4,2,1,11,2,40,8
21,22024,2544,0022400524,"Feb 19, 2025",LAL vs. CHA,L,38,10,22,4,11,2,2,1,6,11,1,2,2,0,26,-4
22,22024,2544,0022400781,"Feb 12, 2025",LAL @ UTA,L,34,6,13,4,8,2,4,1,5,7,1,0,3,3,18,-10
23,22024,2544,0022400768,"Feb 10, 2025",LAL vs. UTA,W,29,10,17,3,7,1,2,1,6,8,1,0,7,2,24,24
24,22024,2544,0022400731,"Feb 06, 2025",LAL vs. GSW,W,38,14,25,6,9,8,10,1,16,8,1,1,3,1,42,7
25,22024,2544,0022400715,"Feb 04, 2025",LAL @ LAC,W,31,8,13,2,4,8,11,0,8,9,3,0,3,4,26,19
26,22024,2544,0022400692,"Feb 01, 2025",LAL @ NYK,W,37,14,26,3,8,2,4,0,11,12,0,0,5,3,33,12
27,22024,2544,0022400674,"Jan 30, 2025",LAL @ WAS,W,27,9,19,1,4,5,5,0,3,11,0,0,0,1,24,29
28,22024,2544,0022400660,"Jan 28, 2025",LAL @ PHI,L,33,10,16,1,4,10,11,1,7,9,1,0,8,1,31,-11
29,22024,2544,0022400648,"Jan 27, 2025",LAL @ CHA,W,36,9,17,1,8,3,5,0,7,8,0,0,5,0,22,-1
30,22024,2544,0022400644,"Jan 25, 2025",LAL @ GSW,W,35,12,25,0,1,1,2,1,4,12,1,0,3,0,25,11
31,22024,2544,0022400629,"Jan 23, 2025",LAL vs. BOS,W,31,9,20,0,2,2,2,3,11,6,0,0,2,0,20,7
32,22024,2544,0022400610,"Jan 21, 2025",LAL vs. WAS,W,36,8,18,2,6,3,3,0,10,13,2,1,5,0,21,19
33,22024,2544,0022400596,"Jan 19, 2025",LAL @ LAC,L,35,9,20,2,6,5,6,2,3,11,3,1,5,3,25,-3
34,22024,2544,0022400585,"Jan 17, 2025",LAL vs. BKN,W,35,12,17,4,6,1,2,1,6,8,1,2,5,2,29,-11
35,22024,2544,0022400570,"Jan 15, 2025",LAL vs. MIA,W,38,9,15,3,6,1,2,1,4,9,2,0,2,0,22,14
36,22024,2544,0022400552,"Jan 13, 2025",LAL vs. SAS,L,32,7,11,2,3,2,4,1,4,8,1,1,7,3,18,-15
37,22024,2544,0022400504,"Jan 07, 2025",LAL @ DAL,L,35,6,12,1,4,5,6,0,10,8,1,0,2,0,18,-12
38,22024,2544,0022400491,"Jan 05, 2025",LAL @ HOU,L,36,8,16,4,7,1,2,1,12,9,1,0,2,4,21,-13
39,22024,2544,0022400477,"Jan 03, 2025",LAL vs. ATL,W,30,13,20,2,5,2,2,0,3,8,0,0,3,3,30,4
40,22024,2544,0022400468,"Jan 02, 2025",LAL vs. POR,W,36,15,25,7,10,1,2,1,2,8,0,0,4,1,38,4
41,22024,2544,0022400454,"Dec 31, 2024",LAL vs. CLE,L,34,9,17,3,6,2,2,0,4,7,0,1,2,1,23,-11
42,22024,2544,0022400408,"Dec 25, 2024",LAL @ GSW,W,37,12,22,2,4,5,5,0,4,10,2,1,1,3,31,4
43,22024,2544,0022400404,"Dec 23, 2024",LAL vs. DET,L,35,10,16,2,4,6,7,2,9,11,0,0,2,1,28,-1
44,22024,2544,0022400376,"Dec 21, 2024",LAL @ SAC,W,34,13,24,1,8,5,6,0,7,6,4,0,4,2,32,10
45,22024,2544,0022400372,"Dec 19, 2024",LAL @ SAC,W,34,8,21,1,4,2,2,0,6,7,0,1,2,1,19,13
46,22024,2544,0022401220,"Dec 15, 2024",LAL vs. MEM,W,34,7,17,3,6,1,4,4,4,8,1,2,5,2,18,0
47,22024,2544,0022400334,"Dec 06, 2024",LAL @ ATL,L,43,14,25,6,11,5,6,0,10,11,2,3,4,3,39,3
48,22024,2544,0022400321,"Dec 04, 2024",LAL @ MIA,L,29,12,18,1,4,4,4,1,4,8,1,0,5,2,29,-21
49,22024,2544,0022400318,"Dec 02, 2024",LAL @ MIN,L,31,4,16,0,4,2,4,3,5,4,0,0,6,1,10,-28
50,22024,2544,0022400311,"Dec 01, 2024",LAL @ UTA,W,36,12,28,0,9,3,3,1,4,14,0,2,3,1,27,0
51,22024,2544,0022400048,"Nov 29, 2024",LAL vs. OKC,L,34,5,13,0,4,2,2,0,8,6,0,0,5,0,12,-12
52,22024,2544,0022400296,"Nov 27, 2024",LAL @ SAS,W,33,8,18,0,2,0,0,3,7,11,1,1,5,0,16,4
53,22024,2544,0022400039,"Nov 26, 2024",LAL @ PHX,L,35,7,16,2,7,2,2,1,7,10,0,0,5,0,18,-30
54,22024,2544,0022400270,"Nov 23, 2024",LAL vs. DEN,L,35,7,17,1,4,3,3,0,6,7,3,0,6,3,18,-25
55,22024,2544,0022400263,"Nov 21, 2024",LAL vs. ORL,L,37,12,22,5,9,2,4,2,8,7,0,1,4,0,31,-8
56,22024,2544,0022400026,"Nov 19, 2024",LAL vs. UTA,W,34,9,17,1,5,7,11,0,2,12,0,0,4,1,26,-5
57,22024,2544,0022400231,"Nov 16, 2024",LAL @ NOP,W,37,8,19,2,7,3,5,4,3,5,1,0,6,1,21,1
58,22024,2544,0022400015,"Nov 15, 2024",LAL @ SAS,W,38,6,12,1,4,2,4,1,15,12,1,0,7,0,15,3
59,22024,2544,0022400225,"Nov 13, 2024",LAL vs. MEM,W,37,13,22,4,7,5,8,1,11,14,1,0,6,2,35,3
60,22024,2544,0022400211,"Nov 10, 2024",LAL vs. TOR,W,35,6,14,0,3,7,7,2,8,16,1,0,3,0,19,13
61,22024,2544,0022400195,"Nov 08, 2024",LAL vs. PHI,W,34,9,14,2,4,1,1,0,12,13,0,3,2,0,21,12
62,22024,2544,0022400174,"Nov 06, 2024",LAL @ MEM,L,35,15,24,6,11,3,4,0,7,6,1,0,5,2,39,-21
63,22024,2544,0022400156,"Nov 04, 2024",LAL @ DET,L,40,7,16,1,2,5,5,1,7,11,2,0,1,1,20,-16
64,22024,2544,0022400137,"Nov 01, 2024",LAL @ TOR,W,36,9,17,5,8,4,6,0,6,10,1,0,0,1,27,11
65,22024,2544,0022400118,"Oct 30, 2024",LAL @ CLE,L,29,9,13,1,3,7,7,1,5,3,0,0,6,2,26,-17
66,22024,2544,0022400111,"Oct 28, 2024",LAL @ PHX,L,36,3,14,2,5,3,6,0,5,8,1,0,2,1,11,-17
67,22024,2544,0022400096,"Oct 26, 2024",LAL vs. SAC,W,34,12,22,4,9,4,4,0,14,10,0,1,5,3,32,13
68,22024,2544,0022400085,"Oct 25, 2024",LAL vs. PHX,W,35,7,13,2,5,5,8,0,4,8,0,0,2,1,21,14
69,22024,2544,0022400062,"Oct 22, 2024",LAL vs. MIN,W,35,7,16,1,4,1,1,0,5,4,0,2,2,3,16,-6

In [14]:
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1

In [16]:
df.drop(columns=['FG_PCT', 'FG3_PCT', 'FT_PCT', 'REB', 'VIDEO_AVAILABLE'])
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1

In [18]:
df['is_home'] = ~df['MATCHUP'].str.contains('@')
df['opponent'] = df['MATCHUP'].str.split().str[-1]

In [19]:
df[['MATCHUP', 'is_home', 'opponent']].head()

       MATCHUP  is_home opponent
0  LAL vs. HOU     True      HOU
1    LAL @ DAL    False      DAL
2    LAL @ OKC    False      OKC
3    LAL @ OKC    False      OKC
4  LAL vs. NOP     True      NOP

In [21]:
df = df.drop(columns=['MATCHUP'])

In [23]:
from nba_api.stats.static import teams

all_teams = teams.get_teams()
team_lookup = {t['abbreviation']: t['id'] for t in all_teams}

df['opponent_team_id'] = df['opponent'].map(team_lookup)

In [24]:
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,is_home,opponent,opponent_team_id
0,22024,2544,0022401185,"Apr 11, 2025",W,22,6,11,0.545,1,4,0.250,1,1,1.000,0,4,4,8,1,0,1,1,14,5,1,True,HOU,1610612745
1,22024,2544,0022401159,"Apr 09, 2025",W,36,11,20,0.550,0,4,0.000,5,6,0.833,2,5,7,3,1,0,2,2,27,18,1,False,DAL,1610612742
2,22024,2544,0022401153,"Apr 08, 2025",L,35,8,19,0.421,3,6,0.500,9,10,0.900,0,7,7,3,1,0,6,1,28,-23,1,False,OKC,1610612760
3,22024,2544,0022401135,"Apr 06, 2025",W,34,9,16,0.563,1,1,1.000,0,0,0.000,2,1,3,7,1,0,2,0,19,7,1,False,OKC,1610612760
4,22024,2544,0022401126,"Apr 04, 2025",W,33,9,17,0.529,2,7,0.286,7,8,0.875,0,0,0,8,2,0,1,1,27,7,1,True,NOP,1610612740

In [25]:
# Get current column order
cols = df.columns.tolist()

# Remove the ones we're relocating, and drop 'opponent' entirely
cols.remove('is_home')
cols.remove('opponent')
cols.remove('opponent_team_id')

# Find where GAME_DATE is, and insert the remaining two columns right after it
insert_at = cols.index('GAME_DATE') + 1
cols[insert_at:insert_at] = ['opponent_team_id', 'is_home']

# Apply the new order (opponent is now excluded)
df = df[cols]

In [26]:
df.columns

Index(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'opponent_team_id',
       'is_home', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE'],
      dtype='str')

In [28]:
df = df.drop(columns=['FG_PCT', 'FG3_PCT', 'FT_PCT', 'REB', 'VIDEO_AVAILABLE'])
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,opponent_team_id,is_home,WL,MIN,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22024,2544,0022401185,"Apr 11, 2025",1610612745,True,W,22,6,11,1,4,1,1,0,4,8,1,0,1,1,14,5
1,22024,2544,0022401159,"Apr 09, 2025",1610612742,False,W,36,11,20,0,4,5,6,2,5,3,1,0,2,2,27,18
2,22024,2544,0022401153,"Apr 08, 2025",1610612760,False,L,35,8,19,3,6,9,10,0,7,3,1,0,6,1,28,-23
3,22024,2544,0022401135,"Apr 06, 2025",1610612760,False,W,34,9,16,1,1,0,0,2,1,7,1,0,2,0,19,7
4,22024,2544,0022401126,"Apr 04, 2025",1610612740,True,W,33,9,17,2,7,7,8,0,0,8,2,0,1,1,27,7

In [29]:
# Look up Bones Hyland (role player, earned rotation spot mid-season — good volatility example)
hyland = players.find_players_by_full_name("Bones Hyland")
hyland_id = hyland[0]['id']

hyland_gamelog = playergamelog.PlayerGameLog(player_id=hyland_id, season='2025-26')
df_hyland = hyland_gamelog.get_data_frames()[0]
df_hyland.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1630538,0022501159,"Apr 08, 2026",MIN @ ORL,L,23,3,8,0.375,3,7,0.429,0,0,0.000,0,1,1,0,1,1,5,1,9,-6,1
1,22025,1630538,0022501152,"Apr 07, 2026",MIN @ IND,W,21,5,9,0.556,4,7,0.571,5,6,0.833,0,4,4,7,1,0,0,3,19,15,1
2,22025,1630538,0022501137,"Apr 05, 2026",MIN vs. CHA,L,29,5,11,0.455,5,11,0.455,3,4,0.750,2,4,6,6,2,1,2,1,18,-1,1
3,22025,1630538,0022501121,"Apr 03, 2026",MIN @ PHI,L,30,7,14,0.500,5,9,0.556,2,3,0.667,0,5,5,3,2,0,1,0,21,-2,1
4,22025,1630538,0022501115,"Apr 02, 2026",MIN @ DET,L,19,3,12,0.250,0,6,0.000,0,0,0.000,0,3,3,2,0,0,1,2,6,9,1

In [30]:
df_hyland['MIN']

0     23
1     21
2     29
3     30
4     19
5     23
6     26
7     30
8     29
9     22
10    25
11    29
12    13
13    11
14    16
15    16
16    23
17    13
18    12
19    16
20    15
21    13
22    14
23    15
24     9
25    15
26    19
27    30
28    26
29    17
30    13
31    23
32    12
33    25
34    16
35    12
36     4
37    13
38    17
39    21
40    12
41    20
42    10
43    12
44    15
45    21
46    13
47    14
48    14
49    23
50    25
51    19
52    16
53    34
54    36
55     5
56    16
57     1
58    10
59     8
60     0
61     6
62     9
63     3
64     5
65    10
66     8
67    16
68    19
69    16
70     8
Name: MIN, dtype: int64

In [ ]:
# Look up Maxime Raynaud (rookie season)
raynaud = players.find_players_by_full_name("Maxime Raynaud")
raynaud_id = raynaud[0]['id']

raynaud_gamelog = playergamelog.PlayerGameLog(player_id=raynaud_id, season='2025-26')
df_raynaud = raynaud_gamelog.get_data_frames()[0]
df_raynaud.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1642875,0022501200,"Apr 12, 2026",SAC @ POR,L,37,7,10,0.700,3,4,0.75,4,4,1.000,2,7,9,2,1,2,3,0,21,-9,1
1,22025,1642875,0022501184,"Apr 10, 2026",SAC vs. GSW,W,39,9,12,0.750,2,4,0.50,3,5,0.600,1,8,9,4,1,0,3,3,23,20,1
2,22025,1642875,0022501154,"Apr 07, 2026",SAC @ GSW,L,26,7,14,0.500,0,1,0.00,3,3,1.000,2,5,7,1,0,0,2,0,17,-4,1
3,22025,1642875,0022501141,"Apr 05, 2026",SAC vs. LAC,L,33,5,12,0.417,0,1,0.00,1,2,0.500,4,11,15,2,1,1,2,1,11,-11,1
4,22025,1642875,0022501128,"Apr 03, 2026",SAC vs. NOP,W,29,11,14,0.786,0,1,0.00,6,7,0.857,2,7,9,4,0,0,1,2,28,1,1

In [32]:
df_raynaud['MIN']

0     37
1     39
2     26
3     33
4     29
5     23
6     32
7     30
8     39
9     30
10    36
11    36
12    42
13    29
14    30
15    25
16    34
17    38
18    26
19    36
20    34
21    32
22    29
23    28
24    26
25    39
26    28
27    38
28    23
29    26
30    21
31    27
32    36
33    19
34    15
35    22
36     9
37    22
38    18
39    23
40    22
41    27
42    31
43    20
44    26
45    35
46    24
47    25
48    35
49    35
50    35
51    27
52    23
53    37
54    31
55    37
56    26
57    37
58    23
59    25
60    32
61    23
62    22
63     9
64    14
65     8
66    21
67    19
68    15
69     5
70    24
71    15
72     4
73    11
Name: MIN, dtype: int64

In [33]:
df_raynaud

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1642875,0022501200,"Apr 12, 2026",SAC @ POR,L,37,7,10,0.700,3,4,0.750,4,4,1.000,2,7,9,2,1,2,3,0,21,-9,1
1,22025,1642875,0022501184,"Apr 10, 2026",SAC vs. GSW,W,39,9,12,0.750,2,4,0.500,3,5,0.600,1,8,9,4,1,0,3,3,23,20,1
2,22025,1642875,0022501154,"Apr 07, 2026",SAC @ GSW,L,26,7,14,0.500,0,1,0.000,3,3,1.000,2,5,7,1,0,0,2,0,17,-4,1
3,22025,1642875,0022501141,"Apr 05, 2026",SAC vs. LAC,L,33,5,12,0.417,0,1,0.000,1,2,0.500,4,11,15,2,1,1,2,1,11,-11,1
4,22025,1642875,0022501128,"Apr 03, 2026",SAC vs. NOP,W,29,11,14,0.786,0,1,0.000,6,7,0.857,2,7,9,4,0,0,1,2,28,1,1
5,22025,1642875,0022501108,"Apr 01, 2026",SAC @ TOR,W,23,2,4,0.500,0,1,0.000,2,2,1.000,0,8,8,0,0,0,1,3,6,1,1
6,22025,1642875,0022501084,"Mar 29, 2026",SAC @ BKN,L,32,4,10,0.400,0,0,0.000,5,8,0.625,2,6,8,2,1,0,1,5,13,-7,1
7,22025,1642875,0022501078,"Mar 28, 2026",SAC @ ATL,L,30,5,8,0.625,2,2,1.000,6,8,0.750,3,7,10,0,1,0,1,1,18,-21,1
8,22025,1642875,0022501065,"Mar 26, 2026",SAC @ ORL,L,39,4,9,0.444,0,1,0.000,2,2,1.000,2,5,7,3,3,0,1,2,10,-2,1
9,22025,1642875,0022501047,"Mar 24, 2026",SAC @ CHA,L,30,6,14,0.429,1,3,0.333,3,4,0.750,0,7,7,0,0,0,2,1,16,-42,1
10,22025,1642875,0022501033,"Mar 22, 2026",SAC vs. BKN,W,36,10,13,0.769,0,0,0.000,2,4,0.500,2,8,10,2,1,1,2,3,22,1,1
11,22025,1642875,0022501015,"Mar 19, 2026",SAC vs. PHI,L,36,11,17,0.647,3,4,0.750,5,5,1.000,1,3,4,2,0,1,0,2,30,-29,1
12,22025,1642875,0022500998,"Mar 17, 2026",SAC vs. SAS,L,42,13,25,0.520,2,5,0.400,4,4,1.000,0,9,9,3,0,1,2,3,32,-22,1
13,22025,1642875,0022500982,"Mar 15, 2026",SAC vs. UTA,W,29,4,8,0.500,0,1,0.000,0,0,0.000,1,11,12,1,0,0,3,3,8,3,1
14,22025,1642875,0022500975,"Mar 14, 2026",SAC @ LAC,W,30,11,12,0.917,0,0,0.000,1,3,0.333,1,4,5,2,0,0,4,3,23,7,1
15,22025,1642875,0022500951,"Mar 11, 2026",SAC vs. CHA,L,25,1,3,0.333,0,0,0.000,2,2,1.000,0,6,6,2,0,3,3,1,4,-18,1
16,22025,1642875,0022500945,"Mar 10, 2026",SAC vs. IND,W,34,8,15,0.533,0,0,0.000,2,2,1.000,3,8,11,2,0,2,1,1,18,2,1
17,22025,1642875,0022500930,"Mar 08, 2026",SAC vs. CHI,W,38,10,20,0.500,0,1,0.000,6,6,1.000,3,8,11,2,1,3,1,3,26,15,1
18,22025,1642875,0022500907,"Mar 05, 2026",SAC vs. NOP,L,26,5,9,0.556,0,0,0.000,0,0,0.000,1,4,5,1,0,0,2,2,10,-5,1
19,22025,1642875,0022500892,"Mar 03, 2026",SAC vs. PHX,L,36,10,12,0.833,0,0,0.000,2,3,0.667,4,6,10,4,2,0,3,4,22,3,1
20,22025,1642875,0022500878,"Mar 01, 2026",SAC @ LAL,L,34,8,10,0.800,0,1,0.000,0,0,0.000,6,7,13,1,0,0,6,3,16,-12,1
21,22025,1642875,0022500854,"Feb 26, 2026",SAC @ DAL,W,32,8,13,0.615,0,1,0.000,6,6,1.000,2,4,6,0,1,1,0,3,22,-5,1
22,22025,1642875,0022500845,"Feb 25, 2026",SAC @ HOU,L,29,5,9,0.556,0,0,0.000,1,2,0.500,3,5,8,2,0,0,1,1,11,-13,1
23,22025,1642875,0022500829,"Feb 23, 2026",SAC @ MEM,W,28,5,9,0.556,0,0,0.000,0,0,0.000,4,9,13,2,0,0,0,0,10,10,1
24,22025,1642875,0022500815,"Feb 21, 2026",SAC @ SAS,L,26,6,14,0.429,0,2,0.000,4,4,1.000,7,5,12,3,0,1,1,4,16,-21,1
25,22025,1642875,0022500800,"Feb 19, 2026",SAC vs. ORL,L,39,8,13,0.615,0,0,0.000,1,1,1.000,3,11,14,4,1,0,1,1,17,-14,1
26,22025,1642875,0022500786,"Feb 11, 2026",SAC @ UTA,L,28,3,7,0.429,0,1,0.000,1,1,1.000,1,3,4,1,1,1,0,2,7,-22,1
27,22025,1642875,0022500766,"Feb 09, 2026",SAC @ NOP,L,38,8,14,0.571,0,1,0.000,5,6,0.833,4,15,19,1,1,0,1,0,21,-16,1
28,22025,1642875,0022500756,"Feb 07, 2026",SAC vs. CLE,L,23,5,8,0.625,0,0,0.000,4,4,1.000,1,6,7,0,2,0,2,1,14,1,1
29,22025,1642875,0022500746,"Feb 06, 2026",SAC vs. LAC,L,26,6,8,0.750,0,1,0.000,0,0,0.000,0,5,5,2,2,0,0,3,12,-5,1
30,22025,1642875,0022500731,"Feb 04, 2026",SAC vs. MEM,L,21,3,5,0.600,0,2,0.000,0,0,0.000,1,4,5,0,0,0,0,1,6,-1,1
31,22025,1642875,0022500707,"Feb 01, 2026",SAC @ WAS,L,27,6,9,0.667,1,1,1.000,1,2,0.500,3,3,6,1,1,2,2,4,14,-1,1
32,22025,1642875,0022500689,"Jan 30, 2026",SAC @ BOS,L,36,6,7,0.857,1,1,1.000,1,1,1.000,3,11,14,1,0,1,2,2,14,-15,1
33,22025,1642875,0022500680,"Jan 29, 2026",SAC @ PHI,L,19,3,4,0.750,0,1,0.000,2,2,1.000,3,4,7,0,1,0,1,5,8,4,1
34,22025,1642875,0022500665,"Jan 27, 2026",SAC @ NYK,L,15,1,2,0.500,0,0,0.000,2,2,1.000,0,3,3,0,0,0,1,1,4,1,1
35,22025,1642875,0022500650,"Jan 25, 2026",SAC @ DET,L,22,1,6,0.167,0,3,0.000,0,0,0.000,0,4,4,0,0,1,2,0,2,-12,1
36,22025,1642875,0022500638,"Jan 23, 2026",SAC @ CLE,L,9,0,2,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,0,1,0,-6,1
37,22025,1642875,0022500626,"Jan 21, 2026",SAC vs. TOR,L,22,3,7,0.429,0,1,0.000,2,2,1.000,1,6,7,2,0,0,1,3,8,-13,1
38,22025,1642875,0022500619,"Jan 20, 2026",SAC vs. MIA,L,18,3,6,0.500,1,1,1.000,0,0,0.000,0,8,8,0,2,0,0,0,7,-6,1
39,22025,1642875,0022500606,"Jan 18, 2026",SAC vs. POR,L,23,3,11,0.273,0,2,0.000,0,0,0.000,3,6,9,1,0,1,0,3,6,-4,1
40,22025,1642875,0022500592,"Jan 16, 2026",SAC vs. WAS,W,22,2,5,0.400,0,0,0.000,0,2,0.000,2,6,8,5,1,0,1,1,4,-7,1
41,22025,1642875,0022500576,"Jan 14, 2026",SAC vs. NYK,W,27,4,6,0.667,0,1,0.000,2,2,1.000,0,4,4,0,0,0,1,1,10,13,1
42,22025,1642875,0022500562,"Jan 12, 2026",SAC vs. LAL,W,31,5,8,0.625,1,2,0.500,0,0,0.000,1,3,4,1,0,0,1,3,11,7,1
43,22025,1642875,0022500557,"Jan 11, 2026",SAC vs. HOU,W,20,6,10,0.600,0,0,0.000,0,0,0.000,3,6,9,1,0,0,1,4,12,8,1
44,22025,1642875,0022500539,"Jan 09, 2026",SAC @ GSW,L,26,4,6,0.667,0,1,0.000,0,0,0.000,2,5,7,2,0,2,2,3,8,-17,1
45,22025,1642875,0022500515,"Jan 06, 2026",SAC vs. DAL,L,35,6,7,0.857,0,0,0.000,2,2,1.000,2,7,9,1,1,0,1,6,14,-6,1
46,22025,1642875,0022500500,"Jan 04, 2026",SAC vs. MIL,L,24,3,5,0.600,0,1,0.000,0,0,0.000,2,6,8,1,0,0,1,2,6,-22,1
47,22025,1642875,0022500483,"Jan 02, 2026",SAC @ PHX,L,25,3,7,0.429,0,0,0.000,0,4,0.000,1,4,5,2,1,0,0,3,6,-19,1
48,22025,1642875,0022500474,"Jan 01, 2026",SAC vs. BOS,L,35,5,8,0.625,0,0,0.000,2,2,1.000,2,6,8,1,0,0,0,2,12,-4,1
49,22025,1642875,0022500461,"Dec 30, 2025",SAC @ LAC,L,35,5,8,0.625,0,1,0.000,2,2,1.000,4,8,12,0,0,2,0,4,12,-21,1
50,22025,1642875,0022500446,"Dec 28, 2025",SAC @ LAL,L,35,8,10,0.800,0,0,0.000,0,1,0.000,2,8,10,2,0,0,2,4,16,-22,1
51,22025,1642875,0022500432,"Dec 27, 2025",SAC vs. DAL,W,27,9,15,0.600,1,1,1.000,0,0,0.000,1,5,6,2,1,2,0,3,19,0,1
52,22025,1642875,0022500421,"Dec 23, 2025",SAC vs. DET,L,23,4,8,0.500,0,1,0.000,0,0,0.000,5,3,8,2,0,1,1,2,8,3,1
53,22025,1642875,0022500401,"Dec 21, 2025",SAC vs. HOU,W,37,6,12,0.500,0,1,0.000,0,0,0.000,4,10,14,0,1,0,2,6,12,3,1
54,22025,1642875,0022500394,"Dec 20, 2025",SAC vs. POR,L,31,7,13,0.538,0,0,0.000,3,4,0.750,6,5,11,1,1,1,5,3,17,-23,1
55,22025,1642875,0022500380,"Dec 18, 2025",SAC @ POR,L,37,10,20,0.500,1,3,0.333,8,9,0.889,4,7,11,2,2,0,2,3,29,-1,1
56,22025,1642875,0022501220,"Dec 14, 2025",SAC @ MIN,L,26,3,6,0.500,0,0,0.000,2,4,0.500,1,5,6,0,0,1,2,4,8,-19,1
57,22025,1642875,0022501208,"Dec 11, 2025",SAC vs. DEN,L,37,7,13,0.538,1,1,1.000,0,2,0.000,3,6,9,1,1,0,1,3,15,-26,1
58,22025,1642875,0022500364,"Dec 08, 2025",SAC @ IND,L,23,5,8,0.625,0,0,0.000,3,4,0.750,3,5,8,3,0,0,3,3,13,2,1
59,22025,1642875,0022500354,"Dec 06, 2025",SAC @ MIA,W,25,6,11,0.545,0,2,0.000,0,0,0.000,1,9,10,1,0,2,0,2,12,12,1
60,22025,1642875,0022500330,"Dec 03, 2025",SAC @ HOU,L,32,10,15,0.667,2,2,1.000,3,3,1.000,2,4,6,3,1,1,1,0,25,-18,1
61,22025,1642875,0022500307,"Nov 30, 2025",SAC vs. MEM,L,23,3,7,0.429,0,1,0.000,3,4,0.750,2,4,6,3,0,1,2,6,9,6,1
62,22025,1642875,0022500077,"Nov 28, 2025",SAC @ UTA,L,22,7,11,0.636,1,2,0.500,4,5,0.800,1,3,4,0,0,1,0,3,19,1,1
63,22025,1642875,0022500068,"Nov 26, 2025",SAC vs. PHX,L,9,0,2,0.000,0,0,0.000,0,0,0.000,1,1,2,0,1,0,0,2,0,-5,1
64,22025,1642875,0022500292,"Nov 24, 2025",SAC vs. MIN,W,14,0,4,0.000,0,1,0.000,1,2,0.500,1,1,2,0,0,0,0,3,1,-5,1
65,22025,1642875,0022500274,"Nov 22, 2025",SAC @ DEN,W,8,3,5,0.600,0,1,0.000,0,0,0.000,0,3,3,1,1,0,0,3,6,-8,1
66,22025,1642875,0022500265,"Nov 20, 2025",SAC @ MEM,L,21,6,8,0.750,0,0,0.000,0,0,0.000,0,3,3,1,0,1,0,2,12,-12,1
67,22025,1642875,0022500261,"Nov 19, 2025",SAC @ OKC,L,19,3,5,0.600,1,1,1.000,0,0,0.000,0,4,4,0,0,0,0,2,7,3,1
68,22025,1642875,0022500223,"Nov 12, 2025",SAC vs. ATL,L,15,3,6,0.500,0,1,0.000,1,1,1.000,1,3,4,1,0,1,3,2,7,-3,1
69,22025,1642875,0022500197,"Nov 09, 2025",SAC vs. MIN,L,5,2,2,1.000,0,0,0.000,1,2,0.500,0,0,0,0,0,0,0,0,5,-2,1
70,22025,1642875,0022500038,"Nov 07, 2025",SAC vs. OKC,L,24,3,10,0.300,0,1,0.000,2,2,1.000,4,6,10,1,1,0,1,1,8,-10,1
71,22025,1642875,0022500181,"Nov 05, 2025",SAC vs. GSW,W,15,1,3,0.333,0,1,0.000,4,4,1.000,1,2,3,0,1,1,1,1,6,1,1
72,22025,1642875,0022500142,"Nov 01, 2025",SAC @ MIL,W,4,0,1,0.000,0,0,0.000,0,0,0.000,1,0,1,0,0,0,0,1,0,0,1
73,22025,1642875,0022500088,"Oct 22, 2025",SAC @ PHX,L,11,0,1,0.000,0,0,0.000,0,0,0.000,0,4,4,2,0,0,1,1,0,-3,1