In [1]:
#solution to fix the missing game logs from a player due to injury/DNP/suspension/unexplained

#using sacramento kings 2025 as test case

In [2]:
import sys
sys.path.append('..')

import pandas as pd

from nbainjuries import injury
from datetime import datetime

from nba_api.stats.static import players
from nba_api.stats.static import teams
from nba_api.stats.endpoints import playergamelog

from scripts.data_cleaning_nba_api import clean_gamelog
from scripts.reorder_columns import reorder_columns
from scripts.data_cleaning_team_schedule import clean_team_schedule

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
from nba_api.stats.endpoints import leaguegamefinder

gamefinder = leaguegamefinder.LeagueGameFinder(
    team_id_nullable=1610612758,
    season_nullable='2025-26'
)
df_sac_schedule = gamefinder.get_data_frames()[0]
df_sac_schedule.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612758,SAC,Sacramento Kings,0022501200,2026-04-12,SAC @ POR,L,240,110,40,83,0.482,7,21,0.333,23,31,0.742,15,32,47,24,7,8,16,18,-12.0
1,22025,1610612758,SAC,Sacramento Kings,0022501184,2026-04-10,SAC vs. GSW,W,241,124,41,89,0.461,17,44,0.386,25,34,0.735,16,33,49,25,10,6,16,21,6.0
2,22025,1610612758,SAC,Sacramento Kings,0022501154,2026-04-07,SAC @ GSW,L,241,105,41,87,0.471,11,31,0.355,12,17,0.706,13,28,41,22,9,6,14,21,-5.0
3,22025,1610612758,SAC,Sacramento Kings,0022501141,2026-04-05,SAC vs. LAC,L,239,109,45,85,0.529,9,32,0.281,10,20,0.500,12,30,42,25,9,8,20,19,-29.0
4,22025,1610612758,SAC,Sacramento Kings,0022501128,2026-04-03,SAC vs. NOP,W,241,117,46,90,0.511,10,33,0.303,15,20,0.750,12,34,46,29,7,6,14,16,4.0

In [4]:
all_teams = teams.get_teams()
team_lookup = {t['abbreviation']: t['id'] for t in all_teams}

In [5]:
df_sac_schedule

#includes pre-season as well (12025) but all we want is the regular seasons (22025)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612758,SAC,Sacramento Kings,0022501200,2026-04-12,SAC @ POR,L,240,110,40,83,0.482,7,21,0.333,23,31,0.742,15,32,47,24,7,8,16,18,-12.0
1,22025,1610612758,SAC,Sacramento Kings,0022501184,2026-04-10,SAC vs. GSW,W,241,124,41,89,0.461,17,44,0.386,25,34,0.735,16,33,49,25,10,6,16,21,6.0
2,22025,1610612758,SAC,Sacramento Kings,0022501154,2026-04-07,SAC @ GSW,L,241,105,41,87,0.471,11,31,0.355,12,17,0.706,13,28,41,22,9,6,14,21,-5.0
3,22025,1610612758,SAC,Sacramento Kings,0022501141,2026-04-05,SAC vs. LAC,L,239,109,45,85,0.529,9,32,0.281,10,20,0.500,12,30,42,25,9,8,20,19,-29.0
4,22025,1610612758,SAC,Sacramento Kings,0022501128,2026-04-03,SAC vs. NOP,W,241,117,46,90,0.511,10,33,0.303,15,20,0.750,12,34,46,29,7,6,14,16,4.0
5,22025,1610612758,SAC,Sacramento Kings,0022501108,2026-04-01,SAC @ TOR,W,239,123,42,92,0.457,12,33,0.364,27,29,0.931,19,29,48,24,7,3,13,22,8.0
6,22025,1610612758,SAC,Sacramento Kings,0022501084,2026-03-29,SAC @ BKN,L,239,99,36,84,0.429,10,32,0.313,17,25,0.680,12,31,43,21,7,3,15,23,-17.0
7,22025,1610612758,SAC,Sacramento Kings,0022501078,2026-03-28,SAC @ ATL,L,239,113,45,93,0.484,12,32,0.375,11,13,0.846,16,26,42,27,7,1,15,18,-10.0
8,22025,1610612758,SAC,Sacramento Kings,0022501065,2026-03-26,SAC @ ORL,L,240,117,45,88,0.511,14,33,0.424,13,16,0.813,9,26,35,30,7,3,9,24,-4.0
9,22025,1610612758,SAC,Sacramento Kings,0022501047,2026-03-24,SAC @ CHA,L,241,90,37,91,0.407,9,28,0.321,7,11,0.636,10,25,35,27,4,3,12,15,-44.0
10,22025,1610612758,SAC,Sacramento Kings,0022501033,2026-03-22,SAC vs. BKN,W,240,126,43,82,0.524,14,27,0.519,26,34,0.765,17,34,51,30,4,5,16,18,4.0
11,22025,1610612758,SAC,Sacramento Kings,0022501015,2026-03-19,SAC vs. PHI,L,240,118,43,89,0.483,12,32,0.375,20,29,0.690,14,27,41,26,3,6,13,18,-21.0
12,22025,1610612758,SAC,Sacramento Kings,0022500998,2026-03-17,SAC vs. SAS,L,241,104,41,93,0.441,14,36,0.389,8,13,0.615,6,35,41,32,4,2,8,14,-28.0
13,22025,1610612758,SAC,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,240,116,41,85,0.482,11,36,0.306,23,28,0.821,12,38,50,28,9,3,18,19,5.0
14,22025,1610612758,SAC,Sacramento Kings,0022500975,2026-03-14,SAC @ LAC,W,241,118,48,82,0.585,12,27,0.444,10,16,0.625,9,39,48,29,9,4,19,25,9.0
15,22025,1610612758,SAC,Sacramento Kings,0022500951,2026-03-11,SAC vs. CHA,L,241,109,45,83,0.542,8,25,0.320,11,14,0.786,8,27,35,24,6,6,13,18,-8.0
16,22025,1610612758,SAC,Sacramento Kings,0022500945,2026-03-10,SAC vs. IND,W,240,114,41,90,0.456,7,20,0.350,25,30,0.833,8,44,52,22,10,7,11,18,5.0
17,22025,1610612758,SAC,Sacramento Kings,0022500930,2026-03-08,SAC vs. CHI,W,241,126,47,105,0.448,11,29,0.379,21,23,0.913,13,42,55,33,5,6,3,21,16.0
18,22025,1610612758,SAC,Sacramento Kings,0022500907,2026-03-05,SAC vs. NOP,L,240,123,50,99,0.505,8,31,0.258,15,23,0.652,10,32,42,29,5,3,7,19,-10.0
19,22025,1610612758,SAC,Sacramento Kings,0022500892,2026-03-03,SAC vs. PHX,L,240,103,41,90,0.456,7,27,0.259,14,18,0.778,13,27,40,25,11,2,14,14,-11.0
20,22025,1610612758,SAC,Sacramento Kings,0022500878,2026-03-01,SAC @ LAL,L,240,104,42,90,0.467,6,26,0.231,14,15,0.933,16,36,52,30,4,8,20,16,-24.0
21,22025,1610612758,SAC,Sacramento Kings,0022500854,2026-02-26,SAC @ DAL,W,240,130,51,101,0.505,8,26,0.308,20,25,0.800,16,30,46,29,11,4,4,22,9.0
22,22025,1610612758,SAC,Sacramento Kings,0022500845,2026-02-25,SAC @ HOU,L,239,97,37,93,0.398,7,32,0.219,16,20,0.800,16,27,43,22,9,2,12,15,-31.0
23,22025,1610612758,SAC,Sacramento Kings,0022500829,2026-02-23,SAC @ MEM,W,241,123,47,94,0.500,10,29,0.345,19,25,0.760,13,32,45,30,12,7,15,15,9.0
24,22025,1610612758,SAC,Sacramento Kings,0022500815,2026-02-21,SAC @ SAS,L,240,122,45,96,0.469,9,32,0.281,23,25,0.920,10,25,35,33,11,7,12,20,-17.0
25,22025,1610612758,SAC,Sacramento Kings,0022500800,2026-02-19,SAC vs. ORL,L,240,94,35,86,0.407,8,27,0.296,16,20,0.800,11,37,48,22,9,3,19,16,-37.0
26,22025,1610612758,SAC,Sacramento Kings,0022500786,2026-02-11,SAC @ UTA,L,240,93,31,90,0.344,7,33,0.212,24,29,0.828,15,27,42,24,10,3,12,15,-28.0
27,22025,1610612758,SAC,Sacramento Kings,0022500766,2026-02-09,SAC @ NOP,L,240,94,40,99,0.404,4,31,0.129,10,15,0.667,19,31,50,19,8,3,14,13,-26.0
28,22025,1610612758,SAC,Sacramento Kings,0022500756,2026-02-07,SAC vs. CLE,L,240,126,48,94,0.511,16,37,0.432,14,20,0.700,15,27,42,30,9,5,15,21,-6.0
29,22025,1610612758,SAC,Sacramento Kings,0022500746,2026-02-06,SAC vs. LAC,L,239,111,41,92,0.446,10,37,0.270,19,22,0.864,12,30,42,22,10,6,11,22,-3.0
30,22025,1610612758,SAC,Sacramento Kings,0022500731,2026-02-04,SAC vs. MEM,L,241,125,45,100,0.450,11,36,0.306,24,28,0.857,14,32,46,29,4,2,13,21,-4.0
31,22025,1610612758,SAC,Sacramento Kings,0022500707,2026-02-01,SAC @ WAS,L,239,112,39,84,0.464,8,21,0.381,26,29,0.897,13,24,37,21,9,8,14,15,-4.0
32,22025,1610612758,SAC,Sacramento Kings,0022500689,2026-01-30,SAC @ BOS,L,241,93,31,83,0.373,10,31,0.323,21,23,0.913,15,32,47,19,4,6,14,18,-19.0
33,22025,1610612758,SAC,Sacramento Kings,0022500680,2026-01-29,SAC @ PHI,L,240,111,41,82,0.500,10,26,0.385,19,23,0.826,15,31,46,21,6,4,16,26,-2.0
34,22025,1610612758,SAC,Sacramento Kings,0022500665,2026-01-27,SAC @ NYK,L,241,87,35,87,0.402,5,30,0.167,12,14,0.857,14,30,44,18,8,3,16,16,-16.0
35,22025,1610612758,SAC,Sacramento Kings,0022500650,2026-01-25,SAC @ DET,L,240,116,44,84,0.524,11,25,0.440,17,28,0.607,12,21,33,32,7,7,19,21,-23.0
36,22025,1610612758,SAC,Sacramento Kings,0022500638,2026-01-23,SAC @ CLE,L,241,118,42,89,0.472,13,33,0.394,21,22,0.955,10,33,43,26,5,2,11,25,-5.0
37,22025,1610612758,SAC,Sacramento Kings,0022500626,2026-01-21,SAC vs. TOR,L,240,109,41,88,0.466,9,33,0.273,18,22,0.818,12,33,45,25,6,6,14,16,-13.0
38,22025,1610612758,SAC,Sacramento Kings,0022500619,2026-01-20,SAC vs. MIA,L,239,117,44,87,0.506,11,30,0.367,18,21,0.857,8,41,49,27,6,4,15,20,-13.0
39,22025,1610612758,SAC,Sacramento Kings,0022500606,2026-01-18,SAC vs. POR,L,242,110,42,86,0.488,11,31,0.355,15,18,0.833,10,30,40,29,8,5,16,26,-7.0
40,22025,1610612758,SAC,Sacramento Kings,0022500592,2026-01-16,SAC vs. WAS,W,241,128,47,81,0.580,15,31,0.484,19,30,0.633,12,33,45,36,5,5,18,19,13.0
41,22025,1610612758,SAC,Sacramento Kings,0022500576,2026-01-14,SAC vs. NYK,W,240,112,35,74,0.473,10,27,0.370,32,38,0.842,9,39,48,23,4,6,15,21,11.0
42,22025,1610612758,SAC,Sacramento Kings,0022500562,2026-01-12,SAC vs. LAL,W,240,124,48,82,0.585,17,26,0.654,11,14,0.786,6,26,32,23,6,4,12,18,12.0
43,22025,1610612758,SAC,Sacramento Kings,0022500557,2026-01-11,SAC vs. HOU,W,241,111,44,91,0.484,8,23,0.348,15,20,0.750,18,27,45,25,4,1,9,22,13.0
44,22025,1610612758,SAC,Sacramento Kings,0022500539,2026-01-09,SAC @ GSW,L,239,103,43,86,0.500,7,27,0.259,10,13,0.769,10,21,31,23,6,6,12,15,-34.0
45,22025,1610612758,SAC,Sacramento Kings,0022500515,2026-01-06,SAC vs. DAL,L,241,98,39,92,0.424,9,31,0.290,11,17,0.647,8,35,43,23,11,6,12,20,-2.0
46,22025,1610612758,SAC,Sacramento Kings,0022500500,2026-01-04,SAC vs. MIL,L,240,98,34,80,0.425,5,25,0.200,25,32,0.781,6,32,38,17,10,7,10,22,-17.0
47,22025,1610612758,SAC,Sacramento Kings,0022500483,2026-01-02,SAC @ PHX,L,242,102,35,85,0.412,10,28,0.357,22,32,0.688,14,28,42,20,6,3,21,23,-27.0
48,22025,1610612758,SAC,Sacramento Kings,0022500474,2026-01-01,SAC vs. BOS,L,241,106,40,85,0.471,12,36,0.333,14,15,0.933,8,24,32,29,7,2,9,17,-14.0
49,22025,1610612758,SAC,Sacramento Kings,0022500461,2025-12-30,SAC @ LAC,L,240,90,34,83,0.410,9,27,0.333,13,14,0.929,11,28,39,18,1,8,18,20,-41.0
50,22025,1610612758,SAC,Sacramento Kings,0022500446,2025-12-28,SAC @ LAL,L,240,101,40,83,0.482,8,29,0.276,13,19,0.684,10,29,39,24,11,3,19,20,-24.0
51,22025,1610612758,SAC,Sacramento Kings,0022500432,2025-12-27,SAC vs. DAL,W,239,113,45,104,0.433,17,38,0.447,6,8,0.750,14,36,50,32,16,7,11,15,6.0
52,22025,1610612758,SAC,Sacramento Kings,0022500421,2025-12-23,SAC vs. DET,L,241,127,42,92,0.457,11,33,0.333,32,37,0.865,19,23,42,26,12,5,13,25,-9.0
53,22025,1610612758,SAC,Sacramento Kings,0022500401,2025-12-21,SAC vs. HOU,W,265,125,44,95,0.463,12,32,0.375,25,36,0.694,19,36,55,29,8,5,11,21,1.0
54,22025,1610612758,SAC,Sacramento Kings,0022500394,2025-12-20,SAC vs. POR,L,240,93,33,87,0.379,6,31,0.194,21,31,0.677,18,32,50,18,14,6,15,19,-5.0
55,22025,1610612758,SAC,Sacramento Kings,0022500380,2025-12-18,SAC @ POR,L,264,133,48,94,0.511,6,19,0.316,31,34,0.912,11,31,42,29,13,7,18,29,-1.0
56,22025,1610612758,SAC,Sacramento Kings,0022501220,2025-12-14,SAC @ MIN,L,240,103,37,81,0.457,10,23,0.435,19,25,0.760,4,32,36,21,5,9,15,21,-14.0
57,22025,1610612758,SAC,Sacramento Kings,0022501208,2025-12-11,SAC vs. DEN,L,240,105,39,87,0.448,11,38,0.289,16,23,0.696,10,28,38,21,9,4,16,20,-31.0
58,22025,1610612758,SAC,Sacramento Kings,0022500364,2025-12-08,SAC @ IND,L,239,105,41,88,0.466,7,22,0.318,16,23,0.696,15,36,51,28,6,4,19,18,-11.0
59,22025,1610612758,SAC,Sacramento Kings,0022500354,2025-12-06,SAC @ MIA,W,239,127,49,93,0.527,14,33,0.424,15,21,0.714,8,37,45,24,11,5,10,19,16.0
60,22025,1610612758,SAC,Sacramento Kings,0022500330,2025-12-03,SAC @ HOU,L,241,95,40,97,0.412,10,34,0.294,5,10,0.500,12,20,32,21,10,7,12,17,-26.0
61,22025,1610612758,SAC,Sacramento Kings,0022500307,2025-11-30,SAC vs. MEM,L,241,107,43,94,0.457,8,27,0.296,13,22,0.591,10,24,34,25,14,7,8,22,-8.0
62,22025,1610612758,SAC,Sacramento Kings,0022500077,2025-11-28,SAC @ UTA,L,241,119,43,96,0.448,10,29,0.345,23,32,0.719,12,32,44,27,9,5,9,22,-9.0
63,22025,1610612758,SAC,Sacramento Kings,0022500068,2025-11-26,SAC vs. PHX,L,241,100,40,86,0.465,12,34,0.353,8,10,0.800,9,32,41,20,9,6,19,17,-12.0
64,22025,1610612758,SAC,Sacramento Kings,0022500292,2025-11-24,SAC vs. MIN,W,265,117,42,97,0.433,7,26,0.269,26,28,0.929,11,38,49,27,9,3,12,21,5.0
65,22025,1610612758,SAC,Sacramento Kings,0022500274,2025-11-22,SAC @ DEN,W,241,128,48,91,0.527,10,30,0.333,22,23,0.957,9,28,37,32,8,3,6,20,5.0
66,22025,1610612758,SAC,Sacramento Kings,0022500265,2025-11-20,SAC @ MEM,L,240,96,37,80,0.463,11,33,0.333,11,15,0.733,4,28,32,24,5,5,16,22,-41.0
67,22025,1610612758,SAC,Sacramento Kings,0022500261,2025-11-19,SAC @ OKC,L,241,99,38,86,0.442,8,28,0.286,15,23,0.652,12,33,45,21,12,0,18,22,-14.0
68,22025,1610612758,SAC,Sacramento Kings,0022500234,2025-11-16,SAC @ SAS,L,241,110,41,87,0.471,12,33,0.364,16,22,0.727,5,32,37,25,10,3,12,17,-13.0
69,22025,1610612758,SAC,Sacramento Kings,0022500044,2025-11-14,SAC @ MIN,L,240,110,41,93,0.441,12,33,0.364,16,27,0.593,13,31,44,32,12,4,15,26,-14.0
70,22025,1610612758,SAC,Sacramento Kings,0022500223,2025-11-12,SAC vs. ATL,L,241,100,36,92,0.391,14,39,0.359,14,18,0.778,9,26,35,22,7,1,18,19,-33.0
71,22025,1610612758,SAC,Sacramento Kings,0022500212,2025-11-11,SAC vs. DEN,L,240,108,41,85,0.482,10,33,0.303,16,23,0.696,9,26,35,31,4,3,10,23,-14.0
72,22025,1610612758,SAC,Sacramento Kings,0022500197,2025-11-09,SAC vs. MIN,L,241,117,40,90,0.444,13,29,0.448,24,31,0.774,12,31,43,25,8,3,16,20,-27.0
73,22025,1610612758,SAC,Sacramento Kings,0022500038,2025-11-07,SAC vs. OKC,L,241,101,38,92,0.413,15,40,0.375,10,15,0.667,8,30,38,27,6,3,15,20,-31.0
74,22025,1610612758,SAC,Sacramento Kings,0022500181,2025-11-05,SAC vs. GSW,W,239,121,41,83,0.494,11,23,0.478,28,33,0.848,8,39,47,27,7,5,16,18,5.0
75,22025,1610612758,SAC,Sacramento Kings,0022500162,2025-11-03,SAC @ DEN,L,240,124,47,90,0.522,9,27,0.333,21,25,0.840,8,39,47,27,5,1,15,24,-6.0
76,22025,1610612758,SAC,Sacramento Kings,0022500142,2025-11-01,SAC @ MIL,W,240,135,45,87,0.517,10,28,0.357,35,40,0.875,11,27,38,30,8,1,9,21,2.0
77,22025,1610612758,SAC,Sacramento Kings,0022500132,2025-10-29,SAC @ CHI,L,241,113,43,82,0.524,7,28,0.250,20,26,0.769,5,26,31,28,10,2,10,17,-13.0
78,22025,1610612758,SAC,Sacramento Kings,0022500126,2025-10-28,SAC @ OKC,L,240,101,36,85,0.424,10,29,0.345,19,21,0.905,9,37,46,21,11,3,17,16,-6.0
79,22025,1610612758,SAC,Sacramento Kings,0022500113,2025-10-26,SAC vs. LAL,L,240,120,45,101,0.446,18,43,0.419,12,18,0.667,13,27,40,27,13,4,15,26,-7.0
80,22025,1610612758,SAC,Sacramento Kings,0022500098,2025-10-24,SAC vs. UTA,W,240,105,40,83,0.482,14,32,0.438,11,15,0.733,5,28,33,23,10,4,13,18,1.0
81,22025,1610612758,SAC,Sacramento Kings,0022500088,2025-10-22,SAC @ PHX,L,240,116,47,94,0.500,9,24,0.375,13,23,0.565,9,28,37,24,10,10,13,22,-4.0
82,12025,1610612758,SAC,Sacramento Kings,0012500007,2025-10-17,SAC @ LAL,W,241,117,41,75,0.547,13,29,0.448,22,28,0.786,5,35,40,26,7,4,16,23,1.0
83,12025,1610612758,SAC,Sacramento Kings,0012500022,2025-10-15,SAC vs. LAC,L,241,91,38,93,0.409,9,42,0.214,6,8,0.750,12,36,48,22,8,1,13,20,-18.0
84,12025,1610612758,SAC,Sacramento Kings,0012500017,2025-10-10,SAC @ POR,L,241,123,43,88,0.489,11,34,0.324,26,33,0.788,12,26,38,20,8,3,17,33,-1.0
85,12025,1610612758,SAC,Sacramento Kings,0012500016,2025-10-08,SAC vs. TOR,L,241,122,42,84,0.500,10,33,0.303,28,37,0.757,9,34,43,25,10,11,18,22,-8.0

In [6]:
#fix to filter out pre-season

df_sac_schedule = df_sac_schedule[
    (df_sac_schedule['SEASON_ID'].astype(str).str.startswith('2')) &
    (df_sac_schedule['SEASON_ID'] == '22025')
]
df_sac_schedule

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612758,SAC,Sacramento Kings,0022501200,2026-04-12,SAC @ POR,L,240,110,40,83,0.482,7,21,0.333,23,31,0.742,15,32,47,24,7,8,16,18,-12.0
1,22025,1610612758,SAC,Sacramento Kings,0022501184,2026-04-10,SAC vs. GSW,W,241,124,41,89,0.461,17,44,0.386,25,34,0.735,16,33,49,25,10,6,16,21,6.0
2,22025,1610612758,SAC,Sacramento Kings,0022501154,2026-04-07,SAC @ GSW,L,241,105,41,87,0.471,11,31,0.355,12,17,0.706,13,28,41,22,9,6,14,21,-5.0
3,22025,1610612758,SAC,Sacramento Kings,0022501141,2026-04-05,SAC vs. LAC,L,239,109,45,85,0.529,9,32,0.281,10,20,0.500,12,30,42,25,9,8,20,19,-29.0
4,22025,1610612758,SAC,Sacramento Kings,0022501128,2026-04-03,SAC vs. NOP,W,241,117,46,90,0.511,10,33,0.303,15,20,0.750,12,34,46,29,7,6,14,16,4.0
5,22025,1610612758,SAC,Sacramento Kings,0022501108,2026-04-01,SAC @ TOR,W,239,123,42,92,0.457,12,33,0.364,27,29,0.931,19,29,48,24,7,3,13,22,8.0
6,22025,1610612758,SAC,Sacramento Kings,0022501084,2026-03-29,SAC @ BKN,L,239,99,36,84,0.429,10,32,0.313,17,25,0.680,12,31,43,21,7,3,15,23,-17.0
7,22025,1610612758,SAC,Sacramento Kings,0022501078,2026-03-28,SAC @ ATL,L,239,113,45,93,0.484,12,32,0.375,11,13,0.846,16,26,42,27,7,1,15,18,-10.0
8,22025,1610612758,SAC,Sacramento Kings,0022501065,2026-03-26,SAC @ ORL,L,240,117,45,88,0.511,14,33,0.424,13,16,0.813,9,26,35,30,7,3,9,24,-4.0
9,22025,1610612758,SAC,Sacramento Kings,0022501047,2026-03-24,SAC @ CHA,L,241,90,37,91,0.407,9,28,0.321,7,11,0.636,10,25,35,27,4,3,12,15,-44.0
10,22025,1610612758,SAC,Sacramento Kings,0022501033,2026-03-22,SAC vs. BKN,W,240,126,43,82,0.524,14,27,0.519,26,34,0.765,17,34,51,30,4,5,16,18,4.0
11,22025,1610612758,SAC,Sacramento Kings,0022501015,2026-03-19,SAC vs. PHI,L,240,118,43,89,0.483,12,32,0.375,20,29,0.690,14,27,41,26,3,6,13,18,-21.0
12,22025,1610612758,SAC,Sacramento Kings,0022500998,2026-03-17,SAC vs. SAS,L,241,104,41,93,0.441,14,36,0.389,8,13,0.615,6,35,41,32,4,2,8,14,-28.0
13,22025,1610612758,SAC,Sacramento Kings,0022500982,2026-03-15,SAC vs. UTA,W,240,116,41,85,0.482,11,36,0.306,23,28,0.821,12,38,50,28,9,3,18,19,5.0
14,22025,1610612758,SAC,Sacramento Kings,0022500975,2026-03-14,SAC @ LAC,W,241,118,48,82,0.585,12,27,0.444,10,16,0.625,9,39,48,29,9,4,19,25,9.0
15,22025,1610612758,SAC,Sacramento Kings,0022500951,2026-03-11,SAC vs. CHA,L,241,109,45,83,0.542,8,25,0.320,11,14,0.786,8,27,35,24,6,6,13,18,-8.0
16,22025,1610612758,SAC,Sacramento Kings,0022500945,2026-03-10,SAC vs. IND,W,240,114,41,90,0.456,7,20,0.350,25,30,0.833,8,44,52,22,10,7,11,18,5.0
17,22025,1610612758,SAC,Sacramento Kings,0022500930,2026-03-08,SAC vs. CHI,W,241,126,47,105,0.448,11,29,0.379,21,23,0.913,13,42,55,33,5,6,3,21,16.0
18,22025,1610612758,SAC,Sacramento Kings,0022500907,2026-03-05,SAC vs. NOP,L,240,123,50,99,0.505,8,31,0.258,15,23,0.652,10,32,42,29,5,3,7,19,-10.0
19,22025,1610612758,SAC,Sacramento Kings,0022500892,2026-03-03,SAC vs. PHX,L,240,103,41,90,0.456,7,27,0.259,14,18,0.778,13,27,40,25,11,2,14,14,-11.0
20,22025,1610612758,SAC,Sacramento Kings,0022500878,2026-03-01,SAC @ LAL,L,240,104,42,90,0.467,6,26,0.231,14,15,0.933,16,36,52,30,4,8,20,16,-24.0
21,22025,1610612758,SAC,Sacramento Kings,0022500854,2026-02-26,SAC @ DAL,W,240,130,51,101,0.505,8,26,0.308,20,25,0.800,16,30,46,29,11,4,4,22,9.0
22,22025,1610612758,SAC,Sacramento Kings,0022500845,2026-02-25,SAC @ HOU,L,239,97,37,93,0.398,7,32,0.219,16,20,0.800,16,27,43,22,9,2,12,15,-31.0
23,22025,1610612758,SAC,Sacramento Kings,0022500829,2026-02-23,SAC @ MEM,W,241,123,47,94,0.500,10,29,0.345,19,25,0.760,13,32,45,30,12,7,15,15,9.0
24,22025,1610612758,SAC,Sacramento Kings,0022500815,2026-02-21,SAC @ SAS,L,240,122,45,96,0.469,9,32,0.281,23,25,0.920,10,25,35,33,11,7,12,20,-17.0
25,22025,1610612758,SAC,Sacramento Kings,0022500800,2026-02-19,SAC vs. ORL,L,240,94,35,86,0.407,8,27,0.296,16,20,0.800,11,37,48,22,9,3,19,16,-37.0
26,22025,1610612758,SAC,Sacramento Kings,0022500786,2026-02-11,SAC @ UTA,L,240,93,31,90,0.344,7,33,0.212,24,29,0.828,15,27,42,24,10,3,12,15,-28.0
27,22025,1610612758,SAC,Sacramento Kings,0022500766,2026-02-09,SAC @ NOP,L,240,94,40,99,0.404,4,31,0.129,10,15,0.667,19,31,50,19,8,3,14,13,-26.0
28,22025,1610612758,SAC,Sacramento Kings,0022500756,2026-02-07,SAC vs. CLE,L,240,126,48,94,0.511,16,37,0.432,14,20,0.700,15,27,42,30,9,5,15,21,-6.0
29,22025,1610612758,SAC,Sacramento Kings,0022500746,2026-02-06,SAC vs. LAC,L,239,111,41,92,0.446,10,37,0.270,19,22,0.864,12,30,42,22,10,6,11,22,-3.0
30,22025,1610612758,SAC,Sacramento Kings,0022500731,2026-02-04,SAC vs. MEM,L,241,125,45,100,0.450,11,36,0.306,24,28,0.857,14,32,46,29,4,2,13,21,-4.0
31,22025,1610612758,SAC,Sacramento Kings,0022500707,2026-02-01,SAC @ WAS,L,239,112,39,84,0.464,8,21,0.381,26,29,0.897,13,24,37,21,9,8,14,15,-4.0
32,22025,1610612758,SAC,Sacramento Kings,0022500689,2026-01-30,SAC @ BOS,L,241,93,31,83,0.373,10,31,0.323,21,23,0.913,15,32,47,19,4,6,14,18,-19.0
33,22025,1610612758,SAC,Sacramento Kings,0022500680,2026-01-29,SAC @ PHI,L,240,111,41,82,0.500,10,26,0.385,19,23,0.826,15,31,46,21,6,4,16,26,-2.0
34,22025,1610612758,SAC,Sacramento Kings,0022500665,2026-01-27,SAC @ NYK,L,241,87,35,87,0.402,5,30,0.167,12,14,0.857,14,30,44,18,8,3,16,16,-16.0
35,22025,1610612758,SAC,Sacramento Kings,0022500650,2026-01-25,SAC @ DET,L,240,116,44,84,0.524,11,25,0.440,17,28,0.607,12,21,33,32,7,7,19,21,-23.0
36,22025,1610612758,SAC,Sacramento Kings,0022500638,2026-01-23,SAC @ CLE,L,241,118,42,89,0.472,13,33,0.394,21,22,0.955,10,33,43,26,5,2,11,25,-5.0
37,22025,1610612758,SAC,Sacramento Kings,0022500626,2026-01-21,SAC vs. TOR,L,240,109,41,88,0.466,9,33,0.273,18,22,0.818,12,33,45,25,6,6,14,16,-13.0
38,22025,1610612758,SAC,Sacramento Kings,0022500619,2026-01-20,SAC vs. MIA,L,239,117,44,87,0.506,11,30,0.367,18,21,0.857,8,41,49,27,6,4,15,20,-13.0
39,22025,1610612758,SAC,Sacramento Kings,0022500606,2026-01-18,SAC vs. POR,L,242,110,42,86,0.488,11,31,0.355,15,18,0.833,10,30,40,29,8,5,16,26,-7.0
40,22025,1610612758,SAC,Sacramento Kings,0022500592,2026-01-16,SAC vs. WAS,W,241,128,47,81,0.580,15,31,0.484,19,30,0.633,12,33,45,36,5,5,18,19,13.0
41,22025,1610612758,SAC,Sacramento Kings,0022500576,2026-01-14,SAC vs. NYK,W,240,112,35,74,0.473,10,27,0.370,32,38,0.842,9,39,48,23,4,6,15,21,11.0
42,22025,1610612758,SAC,Sacramento Kings,0022500562,2026-01-12,SAC vs. LAL,W,240,124,48,82,0.585,17,26,0.654,11,14,0.786,6,26,32,23,6,4,12,18,12.0
43,22025,1610612758,SAC,Sacramento Kings,0022500557,2026-01-11,SAC vs. HOU,W,241,111,44,91,0.484,8,23,0.348,15,20,0.750,18,27,45,25,4,1,9,22,13.0
44,22025,1610612758,SAC,Sacramento Kings,0022500539,2026-01-09,SAC @ GSW,L,239,103,43,86,0.500,7,27,0.259,10,13,0.769,10,21,31,23,6,6,12,15,-34.0
45,22025,1610612758,SAC,Sacramento Kings,0022500515,2026-01-06,SAC vs. DAL,L,241,98,39,92,0.424,9,31,0.290,11,17,0.647,8,35,43,23,11,6,12,20,-2.0
46,22025,1610612758,SAC,Sacramento Kings,0022500500,2026-01-04,SAC vs. MIL,L,240,98,34,80,0.425,5,25,0.200,25,32,0.781,6,32,38,17,10,7,10,22,-17.0
47,22025,1610612758,SAC,Sacramento Kings,0022500483,2026-01-02,SAC @ PHX,L,242,102,35,85,0.412,10,28,0.357,22,32,0.688,14,28,42,20,6,3,21,23,-27.0
48,22025,1610612758,SAC,Sacramento Kings,0022500474,2026-01-01,SAC vs. BOS,L,241,106,40,85,0.471,12,36,0.333,14,15,0.933,8,24,32,29,7,2,9,17,-14.0
49,22025,1610612758,SAC,Sacramento Kings,0022500461,2025-12-30,SAC @ LAC,L,240,90,34,83,0.410,9,27,0.333,13,14,0.929,11,28,39,18,1,8,18,20,-41.0
50,22025,1610612758,SAC,Sacramento Kings,0022500446,2025-12-28,SAC @ LAL,L,240,101,40,83,0.482,8,29,0.276,13,19,0.684,10,29,39,24,11,3,19,20,-24.0
51,22025,1610612758,SAC,Sacramento Kings,0022500432,2025-12-27,SAC vs. DAL,W,239,113,45,104,0.433,17,38,0.447,6,8,0.750,14,36,50,32,16,7,11,15,6.0
52,22025,1610612758,SAC,Sacramento Kings,0022500421,2025-12-23,SAC vs. DET,L,241,127,42,92,0.457,11,33,0.333,32,37,0.865,19,23,42,26,12,5,13,25,-9.0
53,22025,1610612758,SAC,Sacramento Kings,0022500401,2025-12-21,SAC vs. HOU,W,265,125,44,95,0.463,12,32,0.375,25,36,0.694,19,36,55,29,8,5,11,21,1.0
54,22025,1610612758,SAC,Sacramento Kings,0022500394,2025-12-20,SAC vs. POR,L,240,93,33,87,0.379,6,31,0.194,21,31,0.677,18,32,50,18,14,6,15,19,-5.0
55,22025,1610612758,SAC,Sacramento Kings,0022500380,2025-12-18,SAC @ POR,L,264,133,48,94,0.511,6,19,0.316,31,34,0.912,11,31,42,29,13,7,18,29,-1.0
56,22025,1610612758,SAC,Sacramento Kings,0022501220,2025-12-14,SAC @ MIN,L,240,103,37,81,0.457,10,23,0.435,19,25,0.760,4,32,36,21,5,9,15,21,-14.0
57,22025,1610612758,SAC,Sacramento Kings,0022501208,2025-12-11,SAC vs. DEN,L,240,105,39,87,0.448,11,38,0.289,16,23,0.696,10,28,38,21,9,4,16,20,-31.0
58,22025,1610612758,SAC,Sacramento Kings,0022500364,2025-12-08,SAC @ IND,L,239,105,41,88,0.466,7,22,0.318,16,23,0.696,15,36,51,28,6,4,19,18,-11.0
59,22025,1610612758,SAC,Sacramento Kings,0022500354,2025-12-06,SAC @ MIA,W,239,127,49,93,0.527,14,33,0.424,15,21,0.714,8,37,45,24,11,5,10,19,16.0
60,22025,1610612758,SAC,Sacramento Kings,0022500330,2025-12-03,SAC @ HOU,L,241,95,40,97,0.412,10,34,0.294,5,10,0.500,12,20,32,21,10,7,12,17,-26.0
61,22025,1610612758,SAC,Sacramento Kings,0022500307,2025-11-30,SAC vs. MEM,L,241,107,43,94,0.457,8,27,0.296,13,22,0.591,10,24,34,25,14,7,8,22,-8.0
62,22025,1610612758,SAC,Sacramento Kings,0022500077,2025-11-28,SAC @ UTA,L,241,119,43,96,0.448,10,29,0.345,23,32,0.719,12,32,44,27,9,5,9,22,-9.0
63,22025,1610612758,SAC,Sacramento Kings,0022500068,2025-11-26,SAC vs. PHX,L,241,100,40,86,0.465,12,34,0.353,8,10,0.800,9,32,41,20,9,6,19,17,-12.0
64,22025,1610612758,SAC,Sacramento Kings,0022500292,2025-11-24,SAC vs. MIN,W,265,117,42,97,0.433,7,26,0.269,26,28,0.929,11,38,49,27,9,3,12,21,5.0
65,22025,1610612758,SAC,Sacramento Kings,0022500274,2025-11-22,SAC @ DEN,W,241,128,48,91,0.527,10,30,0.333,22,23,0.957,9,28,37,32,8,3,6,20,5.0
66,22025,1610612758,SAC,Sacramento Kings,0022500265,2025-11-20,SAC @ MEM,L,240,96,37,80,0.463,11,33,0.333,11,15,0.733,4,28,32,24,5,5,16,22,-41.0
67,22025,1610612758,SAC,Sacramento Kings,0022500261,2025-11-19,SAC @ OKC,L,241,99,38,86,0.442,8,28,0.286,15,23,0.652,12,33,45,21,12,0,18,22,-14.0
68,22025,1610612758,SAC,Sacramento Kings,0022500234,2025-11-16,SAC @ SAS,L,241,110,41,87,0.471,12,33,0.364,16,22,0.727,5,32,37,25,10,3,12,17,-13.0
69,22025,1610612758,SAC,Sacramento Kings,0022500044,2025-11-14,SAC @ MIN,L,240,110,41,93,0.441,12,33,0.364,16,27,0.593,13,31,44,32,12,4,15,26,-14.0
70,22025,1610612758,SAC,Sacramento Kings,0022500223,2025-11-12,SAC vs. ATL,L,241,100,36,92,0.391,14,39,0.359,14,18,0.778,9,26,35,22,7,1,18,19,-33.0
71,22025,1610612758,SAC,Sacramento Kings,0022500212,2025-11-11,SAC vs. DEN,L,240,108,41,85,0.482,10,33,0.303,16,23,0.696,9,26,35,31,4,3,10,23,-14.0
72,22025,1610612758,SAC,Sacramento Kings,0022500197,2025-11-09,SAC vs. MIN,L,241,117,40,90,0.444,13,29,0.448,24,31,0.774,12,31,43,25,8,3,16,20,-27.0
73,22025,1610612758,SAC,Sacramento Kings,0022500038,2025-11-07,SAC vs. OKC,L,241,101,38,92,0.413,15,40,0.375,10,15,0.667,8,30,38,27,6,3,15,20,-31.0
74,22025,1610612758,SAC,Sacramento Kings,0022500181,2025-11-05,SAC vs. GSW,W,239,121,41,83,0.494,11,23,0.478,28,33,0.848,8,39,47,27,7,5,16,18,5.0
75,22025,1610612758,SAC,Sacramento Kings,0022500162,2025-11-03,SAC @ DEN,L,240,124,47,90,0.522,9,27,0.333,21,25,0.840,8,39,47,27,5,1,15,24,-6.0
76,22025,1610612758,SAC,Sacramento Kings,0022500142,2025-11-01,SAC @ MIL,W,240,135,45,87,0.517,10,28,0.357,35,40,0.875,11,27,38,30,8,1,9,21,2.0
77,22025,1610612758,SAC,Sacramento Kings,0022500132,2025-10-29,SAC @ CHI,L,241,113,43,82,0.524,7,28,0.250,20,26,0.769,5,26,31,28,10,2,10,17,-13.0
78,22025,1610612758,SAC,Sacramento Kings,0022500126,2025-10-28,SAC @ OKC,L,240,101,36,85,0.424,10,29,0.345,19,21,0.905,9,37,46,21,11,3,17,16,-6.0
79,22025,1610612758,SAC,Sacramento Kings,0022500113,2025-10-26,SAC vs. LAL,L,240,120,45,101,0.446,18,43,0.419,12,18,0.667,13,27,40,27,13,4,15,26,-7.0
80,22025,1610612758,SAC,Sacramento Kings,0022500098,2025-10-24,SAC vs. UTA,W,240,105,40,83,0.482,14,32,0.438,11,15,0.733,5,28,33,23,10,4,13,18,1.0
81,22025,1610612758,SAC,Sacramento Kings,0022500088,2025-10-22,SAC @ PHX,L,240,116,47,94,0.500,9,24,0.375,13,23,0.565,9,28,37,24,10,10,13,22,-4.0

In [7]:
# best modular fix: 

from nba_api.stats.endpoints import leaguegamefinder

gamefinder = leaguegamefinder.LeagueGameFinder(
    team_id_nullable=1610612758,
    season_nullable='2025-26',
    season_type_nullable='Regular Season'
)
df_sac_schedule = gamefinder.get_data_frames()[0]
df_sac_schedule.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612758,SAC,Sacramento Kings,0022501200,2026-04-12,SAC @ POR,L,240,110,40,83,0.482,7,21,0.333,23,31,0.742,15,32,47,24,7,8,16,18,-12.0
1,22025,1610612758,SAC,Sacramento Kings,0022501184,2026-04-10,SAC vs. GSW,W,241,124,41,89,0.461,17,44,0.386,25,34,0.735,16,33,49,25,10,6,16,21,6.0
2,22025,1610612758,SAC,Sacramento Kings,0022501154,2026-04-07,SAC @ GSW,L,241,105,41,87,0.471,11,31,0.355,12,17,0.706,13,28,41,22,9,6,14,21,-5.0
3,22025,1610612758,SAC,Sacramento Kings,0022501141,2026-04-05,SAC vs. LAC,L,239,109,45,85,0.529,9,32,0.281,10,20,0.500,12,30,42,25,9,8,20,19,-29.0
4,22025,1610612758,SAC,Sacramento Kings,0022501128,2026-04-03,SAC vs. NOP,W,241,117,46,90,0.511,10,33,0.303,15,20,0.750,12,34,46,29,7,6,14,16,4.0

In [8]:
print(df_sac_schedule.columns.tolist())

['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS']

In [9]:
df_sac_schedule.head(1).T

                                  0
SEASON_ID                     22025
TEAM_ID                  1610612758
TEAM_ABBREVIATION               SAC
TEAM_NAME          Sacramento Kings
GAME_ID                  0022501200
GAME_DATE                2026-04-12
MATCHUP                   SAC @ POR
WL                                L
MIN                             240
PTS                             110
FGM                              40
FGA                              83
FG_PCT                        0.482
FG3M                              7
FG3A                             21
FG3_PCT                       0.333
FTM                              23
FTA                              31
FT_PCT                        0.742
OREB                             15
DREB                             32
REB                              47
AST                              24
STL                               7
BLK                               8
TOV                              16
PF                               18
PLUS_MINUS                    -12.0

In [10]:
# player_status (conceptual, not yet built)
# = team_schedule (every game a team played)
#  LEFT JOIN game_logs ON game_id + player_id
#  → row exists in game_logs? played
#  → row missing? check nbainjuries for that date/player → explained absence or unexplained DNP

In [11]:
raynaud = players.find_players_by_full_name("Maxime Raynaud")
raynaud_id = raynaud[0]['id']

raynaud_gamelog = playergamelog.PlayerGameLog(player_id=raynaud_id, season='2025-26')
df_raynaud = raynaud_gamelog.get_data_frames()[0]
df_raynaud.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,1642875,0022501200,"Apr 12, 2026",SAC @ POR,L,37,7,10,0.700,3,4,0.75,4,4,1.000,2,7,9,2,1,2,3,0,21,-9,1
1,22025,1642875,0022501184,"Apr 10, 2026",SAC vs. GSW,W,39,9,12,0.750,2,4,0.50,3,5,0.600,1,8,9,4,1,0,3,3,23,20,1
2,22025,1642875,0022501154,"Apr 07, 2026",SAC @ GSW,L,26,7,14,0.500,0,1,0.00,3,3,1.000,2,5,7,1,0,0,2,0,17,-4,1
3,22025,1642875,0022501141,"Apr 05, 2026",SAC vs. LAC,L,33,5,12,0.417,0,1,0.00,1,2,0.500,4,11,15,2,1,1,2,1,11,-11,1
4,22025,1642875,0022501128,"Apr 03, 2026",SAC vs. NOP,W,29,11,14,0.786,0,1,0.00,6,7,0.857,2,7,9,4,0,0,1,2,28,1,1

In [12]:
df_raynaud = clean_gamelog(df_raynaud, team_lookup)
df_raynaud.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,opponent_team_id,is_home,WL,MIN,FGM,FGA,FG3M,FG3A,FTM,FTA,OREB,DREB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,22025,1642875,0022501200,"Apr 12, 2026",1610612757,False,L,37,7,10,3,4,4,4,2,7,2,1,2,3,0,21,-9
1,22025,1642875,0022501184,"Apr 10, 2026",1610612744,True,W,39,9,12,2,4,3,5,1,8,4,1,0,3,3,23,20
2,22025,1642875,0022501154,"Apr 07, 2026",1610612744,False,L,26,7,14,0,1,3,3,2,5,1,0,0,2,0,17,-4
3,22025,1642875,0022501141,"Apr 05, 2026",1610612746,True,L,33,5,12,0,1,1,2,4,11,2,1,1,2,1,11,-11
4,22025,1642875,0022501128,"Apr 03, 2026",1610612740,True,W,29,11,14,0,1,6,7,2,7,4,0,0,1,2,28,1

In [13]:
df_sac_schedule = clean_team_schedule(df_sac_schedule, team_lookup)

In [14]:
print(df_sac_schedule.columns.tolist())
print(df_raynaud.columns.tolist())

['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'opponent_team_id', 'is_home', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS']
['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'opponent_team_id', 'is_home', 'WL', 'MIN', 'FGM', 'FGA', 'FG3M', 'FG3A', 'FTM', 'FTA', 'OREB', 'DREB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS']

In [ ]:
#left joining the kings schedule with the raynaud schedule

merged = df_sac_schedule.merge(
    df_raynaud,
    left_on='GAME_ID',
    right_on='Game_ID',
    how='left',
    indicator=True
)

merged[merged['_merge'] == 'left_only']

,SEASON_ID_x,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE_x,opponent_team_id_x,is_home_x,WL_x,MIN_x,PTS_x,FGM_x,FGA_x,FG3M_x,FG3A_x,FTM_x,FTA_x,OREB_x,DREB_x,AST_x,STL_x,BLK_x,TOV_x,PF_x,PLUS_MINUS_x,SEASON_ID_y,Player_ID,Game_ID,GAME_DATE_y,opponent_team_id_y,is_home_y,WL_y,MIN_y,FGM_y,FGA_y,FG3M_y,FG3A_y,FTM_y,FTA_y,OREB_y,DREB_y,AST_y,STL_y,BLK_y,TOV_y,PF_y,PTS_y,PLUS_MINUS_y,_merge
68,22025,1610612758,SAC,Sacramento Kings,0022500234,2025-11-16,1610612759,False,L,241,110,41,87,12,33,16,22,5,32,25,10,3,12,17,-13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
69,22025,1610612758,SAC,Sacramento Kings,0022500044,2025-11-14,1610612750,False,L,240,110,41,93,12,33,16,27,13,31,32,12,4,15,26,-14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
71,22025,1610612758,SAC,Sacramento Kings,0022500212,2025-11-11,1610612743,True,L,240,108,41,85,10,33,16,23,9,26,31,4,3,10,23,-14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
75,22025,1610612758,SAC,Sacramento Kings,0022500162,2025-11-03,1610612743,False,L,240,124,47,90,9,27,21,25,8,39,27,5,1,15,24,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
77,22025,1610612758,SAC,Sacramento Kings,0022500132,2025-10-29,1610612741,False,L,241,113,43,82,7,28,20,26,5,26,28,10,2,10,17,-13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
78,22025,1610612758,SAC,Sacramento Kings,0022500126,2025-10-28,1610612760,False,L,240,101,36,85,10,29,19,21,9,37,21,11,3,17,16,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
79,22025,1610612758,SAC,Sacramento Kings,0022500113,2025-10-26,1610612747,True,L,240,120,45,101,18,43,12,18,13,27,27,13,4,15,26,-7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
80,22025,1610612758,SAC,Sacramento Kings,0022500098,2025-10-24,1610612762,True,W,240,105,40,83,14,32,11,15,5,28,23,10,4,13,18,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [17]:
print(len(gap_dates))

8

In [18]:
#verifying raynaud didn't play in the game listed in the previous cell output 

gap_dates = merged[merged['_merge'] == 'left_only']['GAME_DATE_x'].tolist()

for date_str in gap_dates:
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    report_time = datetime(date_obj.year, date_obj.month, date_obj.day, 17, 30)
    
    try:
        report = injury.get_reportdata(report_time, return_df=True)
        match = report[report['Player Name'].str.contains('Raynaud', case=False, na=False)]
        
        if match.empty:
            print(f"{date_str}: NOT on injury report (likely coach's decision)")
        else:
            print(f"{date_str}: ON injury report — {match['Current Status'].values[0]}, {match['Reason'].values[0]}")
    except Exception as e:
        print(f"{date_str}: report unavailable — {e}")

Validated Injury-Report_2025-11-16_05PM.
2025-11-16: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-11-14_05PM.
2025-11-14: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-11-11_05PM.
2025-11-11: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-11-03_05PM.
2025-11-03: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-10-29_05PM.
2025-10-29: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-10-28_05PM.
2025-10-28: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-10-26_05PM.
2025-10-26: NOT on injury report (likely coach's decision)
Validated Injury-Report_2025-10-24_05PM.
2025-10-24: NOT on injury report (likely coach's decision)

In [20]:
#confirm start/end dates for kings regular season and raynaud regular season

df_raynaud['GAME_DATE'] = pd.to_datetime(df_raynaud['GAME_DATE'])
df_sac_schedule['GAME_DATE'] = pd.to_datetime(df_sac_schedule['GAME_DATE'])

print(df_sac_schedule['GAME_DATE'].min(), df_sac_schedule['GAME_DATE'].max())
print(df_raynaud['GAME_DATE'].min(), df_raynaud['GAME_DATE'].max())

2025-10-22 00:00:00 2026-04-12 00:00:00
2025-10-22 00:00:00 2026-04-12 00:00:00